# Generated by Django 3.2.13 on 2022-11-21 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_article_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communities.article'),
        ),
    ]
