# Generated by Django 3.2.13 on 2022-11-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
