# Generated by Django 3.2.13 on 2022-11-21 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='like_users',
            field=models.ManyToManyField(related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.user'),
            preserve_default=False,
        ),
    ]
