# Generated by Django 3.2.13 on 2022-11-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20221121_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_ids',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='like_users',
        ),
    ]
