# Generated by Django 3.2.13 on 2022-11-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20221121_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre_ids',
        ),
    ]
