# Generated by Django 3.2.13 on 2022-11-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_genres_movie_genre_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_ids',
            new_name='genre_list',
        ),
    ]
