# Generated by Django 3.2.13 on 2022-11-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_genre_ids_movie_genre_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_list',
            new_name='genre_ids',
        ),
    ]
