# Generated by Django 3.2.13 on 2022-11-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_genre_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_ids',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
